---
- hosts: mailserver
  remote_user: admin
  become: yes
  become_method: sudo 
  vars:
    packages:
     - postfix
     - dovecot
     - squirrelmail
     - httpd

  tasks:
  - name: Epel repo is installed
    yum:
      name: epel-release
      state: present 
  
  - name: Install mail packages
    yum:
      name: "{{ packages }}" 
      state: latest  
  
  - name: Configure mail server
    template:
      src: ./postfix-main.cf.j2
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 0644
    notify: Restart postfix

  - name: Mail server running and enabled
    service:
      name: postfix
      state: started
      enabled: true
  
  - name: Open postfix firewall ports
    firewalld:
      service: smtp
      permanent: yes
      state: enabled
      zone: public

  - name: Copy dovecot mail configuration
    copy:
      src: ./10-mail.conf
      dest: /etc/dovecot/conf.d/10-mail.conf
      owner: root
      group: root
      mode: 0644
    notify: Restart dovecot

  - name: Dovecot running and enabled
    service:
      name: dovecot
      state: started
      enabled: true

  - name: Open dovecot firewall port 
    firewalld:
      service: imap
      permanent: yes
      state: enabled
      zone: public

  - name: Configure squirrelmail
    template:
      src: ./squirrelmail.conf.j2
      dest: /etc/squirrelmail/config.php
      owner: root
      group: root
      mode: 0640

  - name: Apache running and enabled
    service:
      name: httpd
      state: started
      enabled: true

  - name: Open http firewall port
    firewalld:
      service: http
      permanent: yes
      state: enabled
      zone: public
  
  handlers: 
  - name: Restart postfix
    service:
      name: postfix
      state: restarted
      enabled: yes 

  - name: Restart dovecot
    service:
      name: dovecot
      state: restarted
      enabled: yes   
      

